### ISSUE TITLE
Support outside (host) connections to guest PG server

### ISSUE THREAD

**Issue by kvirani** [lighthouse-labs/student-image#20]
Need to do 2 things to support local connections from host OS to the guest PG server (eg: pgAdmin):

1. Port forwarding
2. Binding to 0.0.0.0

>khurram [11:38 AM] 
> Karl is telling me the hba_conf needs to tell it to bind to 0.0.0.0 (not 127.x) to support connections from outside (host machine) and also the Vagrantfile needs port 5432 forwarded from host to guest to allow it to actually get in there. The old machine had these, are you cool to put them back in to this one? (edited)

**Comment by kvirani** [comment]
Thanks to @jensen for the tip!

**Comment by interlock** [comment]
Latest image is uploading as I type.

**Comment by kvirani** [comment]
Awesome, thanks man.

Khurram Virani
