### ISSUE TITLE
Support symlink in windows

### ISSUE THREAD

**Issue by interlock** [lighthouse-labs/student-image#24]
```ruby
config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
end
```

**Comment by jholman** [comment]
@vsviridov  probably has information about what problem he encountered; he might recall whether or not this was the solution.  The student in question was Ili (full name Ilinca, ili on slack, @xipascu on github )

**Comment by vsviridov** [comment]
```
config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
```

And the VM would have to be started using Admin Elevation, since it needs admin privileges now
